# Generated by Django 4.1 on 2024-03-23 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=500)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
