# Generated by Django 4.1 on 2024-03-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decription',
            new_name='description',
        ),
    ]
